=== toadervandreea/dataaccess/curs3/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="catalog"/>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="articol" type="TipArticol"
				minoccurs="0" maxoccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="TipArticol">
		<xs:sequence>
			<xs:element name="nume" type="xs:string"
			minoccurs="1" maxoccurs="1"/>
			<xs:element name="categorie" type="xs:string"
			minoccurs="1" maxoccurs="1"/>
			<xs:element name="descriere" type="xs:string"
			minoccurs="0" maxoccurs="1"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int"/>
	</xs:complexType>
</xs:schema>

=== toadervandreea/dataaccess/curs3/catalog5.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="schema.xsd">>
	<articol id="1">
		<nume>Coca Cola</nume>
		<categorie>Băuturi</categorie>
		<descriere><![CDATA[
		Descrierea primului articol
		în format <b>HTML</b>
		]]></descriere>
	</articol>
	<articol id="2">
		<nume>Ciocolată</nume>
		<categorie>Alimente</categorie>
		<descriere><![CDATA[
		Descrierea celui de-al doilea articol
		în format <b>HTML</b>
		]]></descriere>
	</articol>
		<articol id="3">
		<nume>HP Pavilion</nume>
		<categorie>Laptopuri</categorie>
		<descriere><![CDATA[
		Descrierea celui de-al treilea articol
		în format <b>HTML</b>
		]]></descriere>
	</articol>
</catalog>
